
INSERT INTO ROOM(ID, FLOOR, NAME ) VALUES(-10, 1,'Room1' );
INSERT INTO ROOM(ID, FLOOR, NAME ) VALUES(-9, 1,'Room2' );
INSERT INTO ROOM(ID, FLOOR, NAME ) VALUES(-8, 2,'Room3' );
INSERT INTO ROOM(ID, FLOOR, NAME ) VALUES(-7, 2,'Room4' );
INSERT INTO ROOM(ID, FLOOR, NAME ) VALUES(-6, 2,'Room5' );
INSERT INTO ROOM(ID, FLOOR, NAME ) VALUES(-5, 2,'Room6' );
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -8);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -8);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-3, 0, 'OFF', -5);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-4, 0, 'OFF', -8);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-5, 0, 'OFF', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-6, 0, 'OFF', -5);
