INSERT INTO BUILDING(ID, NAME) VALUES(-5, 'Building1');
INSERT INTO BUILDING(ID, NAME) VALUES(-6, 'Building2');
INSERT INTO ROOM(ID, FLOOR, NAME, BUILDING_ID) VALUES(-10, 1,'Room1',-5);
INSERT INTO ROOM(ID, FLOOR, NAME, BUILDING_ID) VALUES(-9, 1,'Room2',-5);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -10);

