INSERT INTO ROOM(ID, FLOOR, NAME) VALUES(-10, 1,'Room1');
INSERT INTO ROOM(ID, FLOOR, NAME) VALUES(-9, 1,'Room2');
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-1, 8, 'ON', -10);
INSERT INTO LIGHT(ID, LEVEL, STATUS, ROOM_ID) VALUES (-2, 0, 'OFF', -10);